import type { Affordability } from "@/lib/diet-planner/constants";
import type { IndianFoodEntry, IndianFoodItem, IndianMealCategory } from "./types";

export type {
  IndianFoodEntry,
  IndianFoodItem,
  IndianMealCategory,
  IndianDietType,
  IndianFoodTag,
} from "./types";

type FoodInput = Omit<IndianFoodItem, "preferredKey"> & { preferredKey?: string };

function food(input: FoodInput): IndianFoodItem {
  return {
    ...input,
    preferredKey: input.preferredKey ?? input.key.replace(/-/g, "_"),
  };
}

export const INDIAN_FOOD_CATALOG: IndianFoodItem[] = [
  // —— Breakfast ——
  food({
    key: "idli-2",
    name: "Idli",
    serving: "2 medium",
    calories: 116,
    proteinG: 4,
    carbsG: 22,
    fatsG: 1,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["breakfast"],
    cuisineTag: "South Indian",
    tags: ["indian", "budget", "south_indian"],
  }),
  food({
    key: "dosa-plain",
    name: "Dosa",
    serving: "1 medium",
    calories: 168,
    proteinG: 4,
    carbsG: 28,
    fatsG: 4,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["breakfast"],
    cuisineTag: "South Indian",
    tags: ["indian", "budget", "south_indian"],
    preferredKey: "dosa",
  }),
  food({
    key: "dosa-masala",
    name: "Masala Dosa",
    serving: "1 medium",
    calories: 220,
    proteinG: 5,
    carbsG: 32,
    fatsG: 7,
    affordability: "moderate",
    dietType: "veg",
    mealCategories: ["breakfast"],
    cuisineTag: "South Indian",
    tags: ["indian", "south_indian"],
    preferredKey: "dosa",
  }),
  food({
    key: "upma-1cup",
    name: "Upma",
    serving: "1 cup",
    calories: 250,
    proteinG: 6,
    carbsG: 38,
    fatsG: 8,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["breakfast"],
    cuisineTag: "South Indian",
    tags: ["indian", "budget", "south_indian"],
    preferredKey: "upma",
  }),
  food({
    key: "poha-1cup",
    name: "Poha",
    serving: "1 cup",
    calories: 270,
    proteinG: 5.5,
    carbsG: 48,
    fatsG: 6,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["breakfast"],
    cuisineTag: "Indian",
    tags: ["indian", "budget"],
    preferredKey: "poha",
  }),
  food({
    key: "pongal-1cup",
    name: "Pongal",
    serving: "1 cup",
    calories: 240,
    proteinG: 7,
    carbsG: 36,
    fatsG: 7,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["breakfast"],
    cuisineTag: "South Indian",
    tags: ["indian", "budget", "south_indian", "comfort"],
    preferredKey: "pongal",
  }),
  food({
    key: "paratha-2",
    name: "Paratha",
    serving: "2 medium",
    calories: 280,
    proteinG: 7,
    carbsG: 38,
    fatsG: 11,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["breakfast", "lunch_dinner"],
    cuisineTag: "North Indian",
    tags: ["indian", "budget", "north_indian"],
    preferredKey: "paratha",
  }),
  food({
    key: "omelette-2eggs",
    name: "Omelette",
    serving: "2 eggs",
    calories: 180,
    proteinG: 12,
    carbsG: 2,
    fatsG: 13,
    affordability: "budget",
    dietType: "non_veg",
    mealCategories: ["breakfast", "protein_sources"],
    cuisineTag: "Indian",
    tags: ["indian", "budget", "high_protein"],
    preferredKey: "eggs",
  }),
  food({
    key: "oats-1bowl",
    name: "Oats",
    serving: "1 bowl with milk",
    calories: 280,
    proteinG: 12,
    carbsG: 42,
    fatsG: 7,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["breakfast"],
    cuisineTag: "Indian",
    tags: ["indian", "budget"],
    preferredKey: "oats",
  }),
  food({
    key: "peanut-chutney-2tbsp",
    name: "Peanut Chutney",
    serving: "2 tbsp",
    calories: 90,
    proteinG: 4,
    carbsG: 4,
    fatsG: 7,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["breakfast", "snacks"],
    cuisineTag: "South Indian",
    tags: ["indian", "budget", "high_protein"],
    preferredKey: "peanut_chutney",
  }),

  // —— Lunch / Dinner ——
  food({
    key: "rice-cooked-1cup",
    name: "Rice",
    serving: "1 cup cooked",
    calories: 205,
    proteinG: 4,
    carbsG: 45,
    fatsG: 0.5,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["lunch_dinner"],
    cuisineTag: "Indian",
    tags: ["indian", "budget"],
    preferredKey: "rice",
  }),
  food({
    key: "rice-brown-1cup",
    name: "Brown Rice",
    serving: "1 cup cooked",
    calories: 215,
    proteinG: 5,
    carbsG: 44,
    fatsG: 1.5,
    affordability: "moderate",
    dietType: "veg",
    mealCategories: ["lunch_dinner"],
    cuisineTag: "Indian",
    tags: ["indian"],
    preferredKey: "brown_rice",
  }),
  food({
    key: "dal-tadka-1cup",
    name: "Dal",
    serving: "1 cup",
    calories: 198,
    proteinG: 9,
    carbsG: 28,
    fatsG: 5,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["lunch_dinner", "protein_sources"],
    cuisineTag: "Indian",
    tags: ["indian", "budget", "high_protein"],
    preferredKey: "dal",
  }),
  food({
    key: "moong-dal-1cup",
    name: "Moong Dal",
    serving: "1 cup",
    calories: 180,
    proteinG: 11,
    carbsG: 24,
    fatsG: 4,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["lunch_dinner", "protein_sources"],
    cuisineTag: "Indian",
    tags: ["indian", "budget", "high_protein"],
    preferredKey: "moong_dal",
  }),
  food({
    key: "chapati-1",
    name: "Chapati",
    serving: "1 medium",
    calories: 120,
    proteinG: 3.5,
    carbsG: 20,
    fatsG: 3,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["lunch_dinner"],
    cuisineTag: "North Indian",
    tags: ["indian", "budget", "north_indian"],
    preferredKey: "chapati",
  }),
  food({
    key: "paneer-curry-1cup",
    name: "Paneer Curry",
    serving: "1 cup",
    calories: 320,
    proteinG: 18,
    carbsG: 12,
    fatsG: 22,
    affordability: "moderate",
    dietType: "veg",
    mealCategories: ["lunch_dinner", "protein_sources"],
    cuisineTag: "North Indian",
    tags: ["indian", "high_protein", "dairy"],
    preferredKey: "paneer",
  }),
  food({
    key: "paneer-palak-1cup",
    name: "Paneer Palak",
    serving: "1 cup",
    calories: 280,
    proteinG: 16,
    carbsG: 10,
    fatsG: 20,
    affordability: "moderate",
    dietType: "veg",
    mealCategories: ["lunch_dinner", "protein_sources"],
    cuisineTag: "North Indian",
    tags: ["indian", "high_protein", "dairy"],
    preferredKey: "paneer",
  }),
  food({
    key: "chicken-curry-1cup",
    name: "Chicken Curry",
    serving: "1 cup",
    calories: 285,
    proteinG: 24,
    carbsG: 8,
    fatsG: 16,
    affordability: "moderate",
    dietType: "non_veg",
    mealCategories: ["lunch_dinner", "protein_sources"],
    cuisineTag: "Indian",
    tags: ["indian", "high_protein"],
    preferredKey: "chicken",
  }),
  food({
    key: "fish-curry-1cup",
    name: "Fish Curry",
    serving: "1 cup",
    calories: 260,
    proteinG: 22,
    carbsG: 6,
    fatsG: 14,
    affordability: "moderate",
    dietType: "non_veg",
    mealCategories: ["lunch_dinner", "protein_sources"],
    cuisineTag: "Coastal Indian",
    tags: ["indian", "high_protein"],
    preferredKey: "fish",
  }),
  food({
    key: "sambar-1cup",
    name: "Sambar",
    serving: "1 cup",
    calories: 130,
    proteinG: 5,
    carbsG: 18,
    fatsG: 4,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["breakfast", "lunch_dinner"],
    cuisineTag: "South Indian",
    tags: ["indian", "budget", "south_indian"],
    preferredKey: "sambar",
  }),
  food({
    key: "rajma-1cup",
    name: "Rajma",
    serving: "1 cup",
    calories: 265,
    proteinG: 13,
    carbsG: 38,
    fatsG: 6,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["lunch_dinner", "protein_sources"],
    cuisineTag: "North Indian",
    tags: ["indian", "budget", "high_protein"],
    preferredKey: "rajma",
  }),
  food({
    key: "chole-1cup",
    name: "Chole",
    serving: "1 cup",
    calories: 280,
    proteinG: 12,
    carbsG: 40,
    fatsG: 7,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["lunch_dinner", "protein_sources"],
    cuisineTag: "North Indian",
    tags: ["indian", "budget", "high_protein"],
    preferredKey: "chole",
  }),
  food({
    key: "curd-rice-1cup",
    name: "Curd Rice",
    serving: "1 cup",
    calories: 220,
    proteinG: 8,
    carbsG: 36,
    fatsG: 5,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["lunch_dinner"],
    cuisineTag: "South Indian",
    tags: ["indian", "budget", "dairy", "comfort"],
    preferredKey: "curd_rice",
  }),
  food({
    key: "biryani-1cup",
    name: "Biryani",
    serving: "1 cup",
    calories: 350,
    proteinG: 14,
    carbsG: 48,
    fatsG: 12,
    affordability: "moderate",
    dietType: "non_veg",
    mealCategories: ["lunch_dinner"],
    cuisineTag: "Hyderabadi",
    tags: ["indian", "comfort"],
    preferredKey: "biryani",
  }),
  food({
    key: "veg-curry-1cup",
    name: "Vegetable Curry",
    serving: "1 cup",
    calories: 120,
    proteinG: 4,
    carbsG: 14,
    fatsG: 6,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["lunch_dinner"],
    cuisineTag: "Indian",
    tags: ["indian", "budget"],
    preferredKey: "vegetables",
  }),
  food({
    key: "spinach-sabzi-1cup",
    name: "Spinach Sabzi",
    serving: "1 cup",
    calories: 80,
    proteinG: 4,
    carbsG: 8,
    fatsG: 4,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["lunch_dinner"],
    cuisineTag: "Indian",
    tags: ["indian", "budget"],
    preferredKey: "spinach",
  }),
  food({
    key: "khichdi-1cup",
    name: "Khichdi",
    serving: "1 cup",
    calories: 230,
    proteinG: 8,
    carbsG: 38,
    fatsG: 5,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["lunch_dinner", "breakfast"],
    cuisineTag: "Indian",
    tags: ["indian", "budget", "comfort"],
    preferredKey: "khichdi",
  }),

  // —— Snacks ——
  food({
    key: "banana-1",
    name: "Banana",
    serving: "1 medium",
    calories: 105,
    proteinG: 1.3,
    carbsG: 27,
    fatsG: 0.4,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["snacks"],
    cuisineTag: "Indian",
    tags: ["indian", "budget", "fruit"],
    preferredKey: "bananas",
  }),
  food({
    key: "dry-fruits-30g",
    name: "Dry Fruits",
    serving: "30 g",
    calories: 170,
    proteinG: 4,
    carbsG: 14,
    fatsG: 11,
    affordability: "moderate",
    dietType: "veg",
    mealCategories: ["snacks"],
    cuisineTag: "Indian",
    tags: ["indian", "high_protein"],
    preferredKey: "dry_fruits",
  }),
  food({
    key: "boiled-eggs-2",
    name: "Boiled Eggs",
    serving: "2 eggs",
    calories: 140,
    proteinG: 12,
    carbsG: 1,
    fatsG: 10,
    affordability: "budget",
    dietType: "non_veg",
    mealCategories: ["snacks", "protein_sources"],
    cuisineTag: "Indian",
    tags: ["indian", "budget", "high_protein"],
    preferredKey: "eggs",
  }),
  food({
    key: "sprouted-moong-salad-1cup",
    name: "Sprouts",
    serving: "1 cup",
    calories: 100,
    proteinG: 7,
    carbsG: 14,
    fatsG: 1,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["snacks", "protein_sources"],
    cuisineTag: "Indian",
    tags: ["indian", "budget", "high_protein"],
    preferredKey: "sprouts",
  }),
  food({
    key: "peanuts-roasted-025cup",
    name: "Roasted Peanuts",
    serving: "1/4 cup",
    calories: 210,
    proteinG: 9,
    carbsG: 6,
    fatsG: 18,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["snacks"],
    cuisineTag: "Indian",
    tags: ["indian", "budget", "high_protein"],
    preferredKey: "peanut_butter",
  }),
  food({
    key: "protein-shake-1",
    name: "Protein Shake",
    serving: "1 glass",
    calories: 180,
    proteinG: 24,
    carbsG: 8,
    fatsG: 3,
    affordability: "moderate",
    dietType: "veg",
    mealCategories: ["snacks", "protein_sources"],
    cuisineTag: "Indian",
    tags: ["indian", "high_protein"],
    preferredKey: "protein_shake",
  }),
  food({
    key: "fruit-bowl-1cup",
    name: "Fruit Bowl",
    serving: "1 cup mixed",
    calories: 120,
    proteinG: 2,
    carbsG: 28,
    fatsG: 0.5,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["snacks"],
    cuisineTag: "Indian",
    tags: ["indian", "budget", "fruit"],
    preferredKey: "fruits",
  }),
  food({
    key: "makhana-1cup",
    name: "Roasted Makhana",
    serving: "1 cup",
    calories: 120,
    proteinG: 4,
    carbsG: 20,
    fatsG: 2,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["snacks"],
    cuisineTag: "Indian",
    tags: ["indian", "budget"],
    preferredKey: "makhana",
  }),
  food({
    key: "apple-1",
    name: "Apple",
    serving: "1 medium",
    calories: 95,
    proteinG: 0.5,
    carbsG: 25,
    fatsG: 0.3,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["snacks"],
    cuisineTag: "Indian",
    tags: ["indian", "budget", "fruit"],
    preferredKey: "apple",
  }),
  food({
    key: "dates-3",
    name: "Dates",
    serving: "3 pieces",
    calories: 90,
    proteinG: 1,
    carbsG: 24,
    fatsG: 0.2,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["snacks"],
    cuisineTag: "Indian",
    tags: ["indian", "budget", "fruit"],
    preferredKey: "dates",
  }),

  // —— Protein sources ——
  food({
    key: "egg-bhurji-2eggs",
    name: "Egg Bhurji",
    serving: "2 eggs",
    calories: 185,
    proteinG: 13,
    carbsG: 4,
    fatsG: 13,
    affordability: "budget",
    dietType: "non_veg",
    mealCategories: ["breakfast", "protein_sources"],
    cuisineTag: "Indian",
    tags: ["indian", "budget", "high_protein"],
    preferredKey: "eggs",
  }),
  food({
    key: "soyachunks-curry-1cup",
    name: "Soy Chunks",
    serving: "1 cup curry",
    calories: 220,
    proteinG: 20,
    carbsG: 18,
    fatsG: 6,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["lunch_dinner", "protein_sources"],
    cuisineTag: "Indian",
    tags: ["indian", "budget", "high_protein"],
    preferredKey: "soy_chunks",
  }),
  food({
    key: "milk-1cup",
    name: "Milk",
    serving: "1 cup",
    calories: 150,
    proteinG: 8,
    carbsG: 12,
    fatsG: 8,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["protein_sources", "snacks"],
    cuisineTag: "Indian",
    tags: ["indian", "budget", "dairy"],
    preferredKey: "milk",
  }),
  food({
    key: "plain-yogurt-1cup",
    name: "Greek Yogurt",
    serving: "1 cup",
    calories: 130,
    proteinG: 15,
    carbsG: 8,
    fatsG: 4,
    affordability: "moderate",
    dietType: "veg",
    mealCategories: ["snacks", "protein_sources"],
    cuisineTag: "Indian",
    tags: ["indian", "high_protein", "dairy"],
    preferredKey: "yogurt",
  }),
  food({
    key: "peanut-butter-2tbsp",
    name: "Peanut Butter",
    serving: "2 tbsp",
    calories: 190,
    proteinG: 8,
    carbsG: 6,
    fatsG: 16,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["snacks", "protein_sources"],
    cuisineTag: "Indian",
    tags: ["indian", "budget", "high_protein"],
    preferredKey: "peanut_butter",
  }),
  food({
    key: "buttermilk-chaas-1glass",
    name: "Buttermilk",
    serving: "1 glass",
    calories: 60,
    proteinG: 3,
    carbsG: 8,
    fatsG: 2,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["snacks"],
    cuisineTag: "Indian",
    tags: ["indian", "budget", "dairy"],
    preferredKey: "buttermilk",
  }),
  food({
    key: "coconut-water-1cup",
    name: "Coconut Water",
    serving: "1 cup",
    calories: 46,
    proteinG: 0.5,
    carbsG: 9,
    fatsG: 0.5,
    affordability: "budget",
    dietType: "veg",
    mealCategories: ["snacks"],
    cuisineTag: "South Indian",
    tags: ["indian", "budget", "fruit"],
    preferredKey: "coconut_water",
  }),
];

/** Legacy export for food logging */
export const INDIAN_FOODS: IndianFoodEntry[] = INDIAN_FOOD_CATALOG.map((f) => ({
  key: f.key,
  name: f.name,
  serving: f.serving,
  calories: f.calories,
  proteinG: f.proteinG,
  carbsG: f.carbsG,
  fatsG: f.fatsG,
}));

const FOODS_BY_NAME = new Map(
  INDIAN_FOOD_CATALOG.map((food) => [food.name.trim().toLowerCase(), food]),
);

const FOODS_BY_KEY = new Map(INDIAN_FOOD_CATALOG.map((food) => [food.key, food]));

const FOODS_BY_PREFERRED_KEY = new Map<string, IndianFoodItem[]>();
for (const item of INDIAN_FOOD_CATALOG) {
  const list = FOODS_BY_PREFERRED_KEY.get(item.preferredKey) ?? [];
  list.push(item);
  FOODS_BY_PREFERRED_KEY.set(item.preferredKey, list);
}

export function findIndianFoodByName(name: string) {
  return FOODS_BY_NAME.get(name.trim().toLowerCase()) ?? null;
}

export function findIndianFoodByKey(key: string) {
  return FOODS_BY_KEY.get(key) ?? null;
}

export function foodsForPreferredKeys(keys: string[]): IndianFoodItem[] {
  const out: IndianFoodItem[] = [];
  const seen = new Set<string>();
  for (const k of keys) {
    for (const f of FOODS_BY_PREFERRED_KEY.get(k) ?? []) {
      if (!seen.has(f.key)) {
        seen.add(f.key);
        out.push(f);
      }
    }
  }
  return out;
}

export function affordabilityRank(a: Affordability) {
  return a === "budget" ? 0 : a === "moderate" ? 1 : 2;
}

export function matchesAffordability(food: IndianFoodItem, max: Affordability) {
  return affordabilityRank(food.affordability) <= affordabilityRank(max);
}

export const MEAL_CATEGORY_LABELS: Record<IndianMealCategory, string> = {
  breakfast: "Breakfast",
  lunch_dinner: "Lunch / Dinner",
  snacks: "Snacks",
  protein_sources: "Protein Sources",
};

export const CUISINE_FILTERS = [
  "All",
  "South Indian",
  "North Indian",
  "Indian",
  "Coastal Indian",
  "Hyderabadi",
] as const;
